### ISSUE TITLE
Better display the BYE in pairings

### ISSUE THREAD

**Issue by pmourlanne** [pmourlanne/taw#37]
WER used to show the BYE with `* * * BYE * * *`, either replicate it, or do something akin to that

Also, the BYE pairing shouldn't have a table number: the player doesn't have to sit anywhere :ok_woman: 

Currently the BYE looks like this:
![Screenshot from 2023-06-14 14-38-48](https://github.com/pmourlanne/taw/assets/3375050/a580dc4b-da7d-4190-949d-7cdaea43d649)

**Comment by stPhena** [comment]
#38 should be a starting point.

**Comment by pmourlanne** [comment]
Closed by https://github.com/pmourlanne/taw/pull/38
